services:
  traefik:
    image: docker.io/library/traefik:v3.4.1
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config.yaml:/etc/traefik/config.yaml:ro
      - ./data/certs/:/var/traefik/certs/:rw
      - ./data/log:/var/log/traefik/:rw
    environment:
      - TZ=Europe/Oslo
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
