services:
  app:
    image: YOUR_IMAGE
    labels:
      - traefik.http.services.app.loadbalancer.server.port=YOUR_PORTNUMBER
      - traefik.enable=true
      - traefik-http.routers.SERVICE_NAME.tls=true
      - traefik.http.routers.SERVICE_NAME.tls.certresolver=cloudflare
      - traefik.http.routers.SERVICE_NAME.entryPoints=websecure
      - traefik.http.routers.SERVICE_NAME.rule=Host(`LOCAL_DOMAIN`)
    networks:
      - proxy

networks:
  proxy:
    external: true